version: '3.9'

services:

  # PostgreSQL
  postgres-intelligent:
    image: postgres:18
    container_name: postgres_intelligent
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: boot
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - contentdb_network

  # Adminer
  adminer:
    image: adminer
    container_name: contentdb_adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - contentdb_network

  # Redis
  redis:
    image: redis:7
    container_name: intelligent_redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - contentdb_network

  # FastAPI
  fastapi-app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres-intelligent:5432/boot
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379/0
    depends_on:
      - postgres-intelligent
      - redis
    networks:
      - contentdb_network
    volumes:
      - ./app:/app/app

# Networks
networks:
  contentdb_network:

# Volumes
volumes:
  postgres_data:
